http:
    port: ${PORT}
rabbitmq:
    user: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    host: ${RABBITMQ_HOST}
    queuename: ${RABBITMQ_QUEUE_NAME}
mail:
    host: ${MAIL_HOST}
    user: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM}
    port: ${MAIL_PORT}